###
### Get all dogs
###

GET http://localhost:5173/api/dogs

###
### Get a specific dog by ID
###

GET http://localhost:5173/api/dogs/3

###
### Create a new dog
###

POST http://localhost:5173/api/dogs
Content-Type: application/json

{
  "name": "Vaca"
}

###
### Update an existing dog
###

PUT http://localhost:5173/api/dogs/4
Content-Type: application/json

{
  "name": "Vaquita",
  "age": 3
}

###
### Delete a dog
###
DELETE http://localhost:5173/api/dogs/5

###
### Delete all dogs
###
DELETE http://localhost:5173/api/dogs
